title:            Daniel Varon
tagline:          
description:      Harvard PhD student in atmospheric chemistry.
canonical: http://www.varon.org

# Owner/author information
owner:
  name:           Daniel Varon
  avatar:         avatar.png
  bio:            "PhD student"
  email:          danielvaron@g.harvard.edu
  #twitter:        twnsndco
  #github:         coletownsend
  #instagram:      ctrunsthis
  #dribbble:       coletownsend
  #disqus:         balzac
  location:       "Cambridge, MA"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
 #- title: Github
 #  url: https://github.com/ColeTownsend/Balzac-for-Jekyll
 #  external: true
  - title: Research
    url: /research
  - title: CV
    url: /cv.pdf
 # - title: Articles
  #  url: /articles

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
